@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3MzQyMTEwMCwiZXhwIjoxNzczNDIyMDAwfQ.eGeQLYNNpV-5lwOHrit6ojWgooMxF4m17iQbEVNkVAs

### 用户登录
POST http://localhost:3000/users/login
content-type: application/json

{
    "account":"ycx123",
    "passWord":"123456"
}

### 用户信息获取
GET http://localhost:3000/users/1
Authorization:Bearer {{token}}
